apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: config-default
  namespace: $NAMESPACE
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: $SECRET_NAME
